import { expect, test } from '@playwright/test';

test('Settings localizes all sections and persists language and appearance', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Cài đặt hiển thị', exact: true }).click();
  const settings = page.locator('.settings-panel');
  await expect(settings).toBeVisible();
  await expect.poll(()=>settings.evaluate(el=>getComputedStyle(el).opacity)).toBe('1');
  await page.screenshot({ path: info.outputPath('settings-vi.png') });
  await settings.getByRole('button', { name: 'English', exact: true }).click();
  await expect(settings).toHaveAttribute('aria-label', 'Settings');
  await expect(settings.getByRole('tab', { name: 'General', exact: true })).toBeVisible();
  await settings.getByRole('button', { name: 'Light', exact: true }).click();
  await expect(settings.getByRole('button', { name: 'Light', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await settings.getByRole('tab', { name: 'Navigation', exact: true }).click();
  await expect(settings.getByRole('button', { name: 'Restore defaults' })).toBeVisible();
  await settings.getByRole('tab', { name: 'BIM–GIS', exact: true }).click();
  await expect(settings.getByLabel('Public access token (pk.)')).toBeVisible();
  await settings.getByRole('tab', { name: 'Storage', exact: true }).click();
  await expect(settings.getByRole('button', { name: 'Clear model cache' })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Display settings', exact: true }).click();
  await expect(settings.getByRole('button', { name: 'English', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(settings.getByRole('button', { name: 'Light', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: info.outputPath('settings-en-light.png') });
  await settings.getByRole('button', { name: 'Tiếng Việt', exact: true }).click();
  await settings.getByRole('tab', { name: 'Bộ nhớ', exact: true }).click();
  await expect(settings).toContainText('Bộ nhớ mô hình');
  await expect(settings.getByRole('button', { name: 'Dọn bộ nhớ mô hình' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('compound BIM filters select and isolate the complete group and survive panel toggles', async ({ page }, info) => {
  test.skip(!process.env.IFC_E2E_GROUP_FIXTURE,'Set IFC_E2E_GROUP_FIXTURE or use run-bim-gis-checks.mjs');
  test.setTimeout(90_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => window.addEventListener('ifc-viewer-ready', (event: any) => { (window as any).viewer = event.detail; }));
  await page.goto('/?viewerDebug=1');
  await page.locator('input[type=file]').setInputFiles(process.env.IFC_E2E_GROUP_FIXTURE!);
  await expect.poll(() => page.evaluate(async () => (window as any).viewer?.model ? await (window as any).viewer.model.getItemsIdsWithGeometry() : []), { timeout:60_000 }).toEqual([5,43,47]);
  await expect.poll(() => page.evaluate(async () => (await (await fetch('/model/runtime')).json()).coldIndexStatus), { timeout: 60_000 }).toBe('ready');
  await page.getByRole('button', { name: 'Project Browser', exact: true }).click();
  const panel = page.getByRole('complementary', { name: 'Project Browser' });
  await panel.getByRole('button', { name: 'Model', exact: true }).click();
  await panel.getByLabel('Set name', { exact: true }).fill('Pset_Phase3Benchmark');
  await panel.getByLabel('Property name', { exact: true }).fill('Profile');
  await panel.getByLabel('Property value', { exact: true }).fill('PL 10x200');
  await panel.getByRole('button', { name: '+ Điều kiện', exact: true }).click();
  await panel.getByLabel('Set name 2', { exact: true }).fill('Pset_GroupSelection');
  await panel.getByLabel('Property name 2', { exact: true }).fill('Zone');
  await panel.getByLabel('Property value 2', { exact: true }).fill('A');
  await panel.getByRole('button', { name: 'Áp dụng', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('2 kết quả · 2 có thể chọn');
  await panel.getByRole('button', { name: 'Chọn kết quả', exact: true }).click();
  await expect.poll(() => page.evaluate(() => (window as any).viewer.captureViewState().selection.map((r: any) => r.localId).sort((a: number,b: number)=>a-b))).toEqual([5,43]);
  await panel.getByRole('button', { name: 'Cô lập', exact: true }).click();
  await expect.poll(() => page.evaluate(async () => (await (window as any).viewer.model.getVisible([5,43,47])))).toEqual([true,true,false]);
  await panel.getByLabel('Tree scope').selectOption('visible');
  await expect(panel.getByRole('tree')).not.toContainText('Group Beam C');
  await panel.getByLabel('Tree scope').selectOption('all');
  await panel.getByRole('button', { name: 'Hiện tất cả', exact: true }).click();
  await expect.poll(() => page.evaluate(async () => (await (window as any).viewer.model.getVisible([5,43,47])))).toEqual([true,true,true]);
  await page.getByRole('button', { name: 'Project Browser', exact: true }).click();
  await expect(panel).toBeHidden();
  await page.getByRole('button', { name: 'Project Browser', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('2 kết quả');
  await expect(panel.getByLabel('Property value 2')).toHaveValue('A');
  await panel.getByLabel('Search tree').fill('Group Beam B');
  await expect(panel.getByRole('status')).toContainText('1 có thể chọn');
  await panel.getByRole('button', { name: 'Chọn kết quả', exact: true }).click();
  await expect.poll(() => page.evaluate(() => (window as any).viewer.captureViewState().selection.map((r: any) => r.localId))).toEqual([43]);
  await panel.getByLabel('Search tree').fill('');
  await panel.getByLabel('Property value 2').fill('B');
  await expect(panel.getByRole('button', { name: 'Chọn kết quả', exact: true })).toHaveCount(0);
  await panel.getByLabel('Kết hợp điều kiện').selectOption('any');
  await panel.getByRole('button', { name: 'Áp dụng', exact: true }).click();
  await expect(panel.getByRole('status')).toContainText('3 kết quả · 3 có thể chọn');
  await panel.getByRole('button', { name: 'Chọn kết quả', exact: true }).click();
  await expect.poll(() => page.evaluate(() => (window as any).viewer.captureViewState().selection.length)).toBe(3);
  await page.screenshot({ path: info.outputPath('bim-group-selection.png') });
  expect(errors).toEqual([]);
});
