"""Compatibility facade for the IFC model services.

New code should import from ``ifc_units``, ``model_cache``, ``model_runtime``,
or ``ifc_elements``. This module preserves the recovered import surface while
the application migrates to the smaller services.
"""

from ifc_elements import (
    _build_geometry,
    build_semantic_record,
    direct_children,
    extract_element,
    extract_element_by_express_id,
)
from ifc_units import (
    ProjectUnits,
    _has_unit_type,
    _lengths_to_m,
    _named_unit_scale_to_si,
    _normalise_quantities,
    _project_unit_scale_to_si,
    _to_kilograms,
    project_units,
)
from model_cache import (
    CACHE_DIR,
    CACHE_KEEP_MODELS,
    CACHE_MAX_BYTES,
    _cache_max_bytes,
    _cache_keep_models,
    _enforce_cache_retention,
    _ensure_cache_dir,
    _fragments_cache_path,
    cached_fragments_file,
    cached_model_file,
    model_source_path,
    store_cached_fragments_commit,
    store_cached_fragments_start,
)
from model_runtime import (
    LIVE_MODEL_IDLE_SECONDS,
    LIVE_MODEL_MAX_BYTES,
    ActiveModel,
    HashMismatchError,
    IndexPreparingError,
    NoActiveModelError,
    _ActiveModelState,
    _PrepareState,
    _activate,
    _activate_in_background,
    _prepare,
    _run_build,
    _should_open_for_geometry,
    _state,
    active_index,
    get_active_model_info,
    live_model_status,
    locate_live_element,
    materialize_model_file,
    materialize_model_stream,
    now_utc,
    open_active_model,
    register_model,
    release_idle_model,
)


__all__ = [
    "ActiveModel",
    "CACHE_DIR",
    "CACHE_KEEP_MODELS",
    "CACHE_MAX_BYTES",
    "HashMismatchError",
    "IndexPreparingError",
    "LIVE_MODEL_IDLE_SECONDS",
    "LIVE_MODEL_MAX_BYTES",
    "NoActiveModelError",
    "ProjectUnits",
    "active_index",
    "build_semantic_record",
    "cached_fragments_file",
    "cached_model_file",
    "direct_children",
    "extract_element",
    "extract_element_by_express_id",
    "get_active_model_info",
    "live_model_status",
    "locate_live_element",
    "materialize_model_file",
    "materialize_model_stream",
    "model_source_path",
    "now_utc",
    "open_active_model",
    "project_units",
    "register_model",
    "release_idle_model",
    "store_cached_fragments_commit",
    "store_cached_fragments_start",
]
